apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    app: demo
    env: staging
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    name: web
    targetPort: 5000
  selector:
    name: web
    app: demo
    env: staging
