apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  template:
    metadata:
      labels:
          name: web
          app: demo
          env: staging
    spec:
      containers:
      - name: web
        image: stealthizer/k8s-tester
        ports:
        - containerPort: 5000
